# Generated by Django 5.2.6 on 2025-09-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=40, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=40, verbose_name='Apellido Materno')),
                ('direccion', models.CharField(max_length=100, null=True, verbose_name='Dirección')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto')),
            ],
        ),
    ]
