# Generated by Django 5.2.6 on 2025-09-23 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Lenguaje')),
            ],
        ),
        migrations.CreateModel(
            name='SO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='SO')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('edad', models.IntegerField(max_length=4, verbose_name='Edad')),
                ('area', models.CharField(choices=[('Front', 'Front'), ('Backend', 'Backend'), ('FullStack', 'FullStack')], max_length=50, verbose_name='Area')),
                ('lenguaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.lenguaje', verbose_name='Lenguaje')),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.so', verbose_name='SO')),
            ],
        ),
    ]
