# Generated by Django 5.2.6 on 2025-09-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto'),
        ),
    ]
